# BOOSTERS
stiffy-base:
  prompt: 'score_9, score_8_up, score_7_up'
  negative_prompt: 'score_4, score_5, score_6, jpeg artifacts, (censor),blurry, lowres, watermark, text, artist tag, words, lowres, ugly, deformed, out of frame, low res, jpeg, bad teeth, ugly teeth,(low quality:0.8), (worst quality:1.4), (bad quality:0.8), source_cartoon, monochrome'
  category: 'boosters'
stiffy-base-lite:
  prompt: 'score_9, score_8_up, score_7_up'
  negative_prompt: 'score_4, score_5, score_6'
  category: 'boosters'
# SUBJECT
# ATTRIBUTES:
# ___________
# ACTION
# BODY
stiffy-mechanical-body:
  prompt: '(mechanical body:1.1), robot body, prosthetic limbs, [:(intricate mechanical body:1.2):5]'
  negative_prompt: ''
  category: 'body'
# FACE
# EXPRESSION
# CLOTHING
# SCENE:
# ______
# ENVIRONMENT
# LIGHTNING
# STYLE:
# ______
# AESTHETIC
stiffy-realistic:
  prompt: 'realistic, real'
  negative_prompt: 'deformed, deformed face, low quality, bad quality, worst quality, (drawn, furry, illustration, cartoon, anime, comic:1.5), 3d, cgi, extra fingers, (source_anime, source_cartoon, source_furry, source_western, source_comic, source_pony), deformed teeth'
  category: 'aesthetic'
# ARTIST
# MEDIUM
# CAMERA
# MOOD
